
services:
  backend:
    build: ./backend  # Собираем образ из папки backend
    ports:
      - "5880:5880"  # Открываем порт 5880
    environment:
      - LANG=ru_RU.UTF-8
      - LC_ALL=ru_RU.UTF-8

  redis:
    image: redis:alpine  # Используем готовый образ Redis

  nginx:
    image: nginx:alpine
    ports:
      - "88:88"  # Открываем порт 80 для веба
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Подключаем конфиг
      - ./frontend:/usr/share/nginx/html  # Подключаем фронтенд
    depends_on:
      - backend  # Запускаем после бэкенда